times = ("sao palo", "corinthians", "palmeiras", "santos", "gremio", "cruzeiro", "flamengo", "vasco", "chapecoense", )
print("=-" * 30)
print(f"lidta de times do brasileirao: {times}")
print("=-" * 30)
print(f"os 5 primeiros numero sao {times[0:5]}")
print("=-" * 30)
print(f"os quatro ultimos sao {times[-4:]}")
print("=-" * 30)
print(f"Times em ordem alfabetica: {sorted(times)}")